
# Spring Boot configuration for REST-SOAP Converter
spring:
  application:
    name: rest-soap-converter

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/restconvertor
    username: postgres
    password: coral@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 300000
      leak-detection-threshold: 60000
      validation-timeout: 3000
      connection-test-query: SELECT 1

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        hbm2ddl:
          auto: update
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    generate-ddl: true

  # Flyway configuration - ENABLED but configured properly
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial baseline
    create-schemas: true
    mixed: true
    validate-on-migrate: true
    clean-on-validation-error: false
    repair-on-migrate: true
    # Add connection retry for database creation race condition
    connect-retries: 3
    connect-retries-interval: 5

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway,beans,env
  endpoint:
    health:
      show-details: always
      show-components: always
    flyway:
      enabled: true

# Logging configuration
logging:
  level:
    com.example.restsoapconverter: INFO
    org.springframework.ws: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.flywaydb: INFO
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application-specific configuration
converter:
  default-timeout-ms: 30000
  max-parallel-calls: 10

# Database management configuration
database:
  auto-create: true
  auto-migrate: true
  connection-retry:
    max-attempts: 3
    delay-ms: 5000
