# Spring Boot configuration for REST-SOAP Converter
spring:
  application:
    name: rest-soap-converter

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: coral@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # Flyway configuration
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.example.restsoapconverter: INFO
    org.springframework.ws: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application-specific configuration
converter:
  default-timeout-ms: 30000
  max-parallel-calls: 10
